backend:
  name: test-repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "accommodation"
    label: "üè® –ù–æ–º–µ—Ä–∞"
    files:
      - name: "accommodation"
        label: "20 –Ω–æ–º–µ—Ä–æ–≤"
        file: "accommodation.json"
        fields:
          - label: "–ù–æ–º–µ—Ä–∞ (–º–∞—Å—Å–∏–≤)"
            name: "root"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "–ù–∞–∑–≤–∞–Ω–∏–µ", name: "name", widget: "string"}
              - {label: "–¶–µ–Ω–∞", name: "priceRange", widget: "string"}
              - {label: "–§–æ—Ç–æ", name: "imageThumb", widget: "image"}
