backend:
  name: test-repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "accommodation"
    label: "üè® –ù–æ–º–µ—Ä–∞"
    files:
      - name: "accommodation"
        label: "–ù–æ–º–µ—Ä–∞"
        file: "accommodation.json"
        fields:
          - label: "–ù–æ–º–µ—Ä–∞"
            name: "body"
            widget: "object"
            fields:
              - label: "–°–ø–∏—Å–æ–∫ –Ω–æ–º–µ—Ä–æ–≤"
                name: "rooms"
                widget: "list"
                fields:
                  - {label: "ID", name: "id", widget: "string"}
                  - {label: "–ù–∞–∑–≤–∞–Ω–∏–µ", name: "name", widget: "string"}
                  - {label: "–¶–µ–Ω–∞", name: "priceRange", widget: "string"}
