backend:
  name: test-repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "data"
    label: "üìÑ JSON —Ñ–∞–π–ª—ã"
    files:
      - label: "üè® –ù–æ–º–µ—Ä–∞"
        name: "accommodation"
        file: "accommodation.json"
        fields:
          - {label: "JSON", name: "body", widget: "markdown"}
      - label: "üí∞ –¶–µ–Ω—ã"
        name: "price"
        file: "price.json"
        fields:
          - {label: "JSON", name: "body", widget: "markdown"}
      - label: "üì∏ –ì–∞–ª–µ—Ä–µ—è"
        name: "gallery"
        file: "gallery.json"
        fields:
          - {label: "JSON", name: "body", widget: "markdown"}
