backend:
  name: test-repo

collections:
  - name: "data"
    label: "ğŸ“„ Ğ ĞµĞ´Ğ°ĞºÑ‚Ğ¸Ñ€Ğ¾Ğ²Ğ°Ñ‚ÑŒ JSON"
    files:
      - {label: "ğŸ¨ ĞĞ¾Ğ¼ĞµÑ€Ğ°", name: "accommodation", file: "accommodation.json", field: {label: "JSON", name: "body", widget: "markdown"}}
      - {label: "ğŸ’° Ğ¦ĞµĞ½Ñ‹", name: "price", file: "price.json", field: {label: "JSON", name: "body", widget: "markdown"}}
      - {label: "ğŸ“¸ Ğ“Ğ°Ğ»ĞµÑ€ĞµÑ", name: "gallery", file: "gallery.json", field: {label: "JSON", name: "body", widget: "markdown"}}
